@startmindmap
* Tecnologia da Informação
** Conceito e Definição
*** Recursos utilizados
**** Criar
**** Processar
**** Armazenar
**** Recuperar
**** Trocar dados e informações
*** Sistemas de TI
**** Hardware
**** Software
**** Equipamentos periféricos
** Histórico da TI
*** Pré-mecânica (3000 a.C. - 1450 d.C.)
*** Mecânica (1450 - 1840)
*** Eletromecânica (1840 - 1940)
*** Eletrônica (1940 - Presente)
** Impactos na Empresa
*** Redefinição de Sistemas
**** Produtivos
**** Gerenciais
*** Mudanças Mercadológicas
**** Estratégias
**** Qualidade
**** Diferenciação
*** Integração de Atividades
**** Networks
**** Competitividade
**** Armazenamento de Dados
** Impactos na Segurança Empresarial
*** Gestão da Segurança
**** Recursos Disponíveis
**** Possibilidades Ilimitadas
**** Portas para o Mundo
*** Era Tecnológica
**** Gestão do Conhecimento
**** Criação
**** Inovação
**** Funcionalidade
** Dispositivos Móveis em Ambientes Corporativos
*** Conectividade e Mobilidade
**** Smartphones
**** Notebooks
**** Tablets
*** Vantagens Empresariais
**** Acesso e Divulgação
**** Redução de Custos
**** Aumento de Produtividade
**** Armazenamento de Dados
** Impactos na Saúde
*** Tomada de Decisões
**** Informação Eficaz
**** Sistemas de Informação
*** Direitos Humanos
**** Desigualdades de Acesso
**** Plataforma de Ação
**** Desenvolvimento Sanitário
** Evolução da TI
*** Processamento de Dados (década de 1960)
*** Sistemas de Informação (década de 1970)
*** Inovação e Vantagem Competitiva (década de 1980)
*** Integração e Reestruturação do Negócio (década de 1990)
** A Era do Processamento de Dados
*** Computadores Limitados
*** Avanços no Hardware
*** Linhas Telefônicas
*** Automatização de Atividades
** A Era dos Sistemas de Informação
*** Transformação de Dados em Informação
*** Melhoria e Adequação de Sistemas
*** Pacotes de Software
*** Sistemas de Apoio à Decisão
** A Era da Inovação e Vantagem Competitiva
*** Microcomputadores
*** Gerenciadores de Banco de Dados
*** Mercado em Busca de Novas Estratégias
*** Uso da TI nas Empresas
** Aprimoramento dos Processos de Negócios
*** Otimização de Processos
*** Eficiência e Otimização
*** Vantagem Competitiva
*** Acesso Facilitado à Informação
*** Melhoria na Qualidade
** A Era da Integração e Reestruturação do Negócio
*** Sistemas Abertos
*** Integração Tecnológica
*** Troca e Acesso a Informações
*** Sistema EDI
** Segurança
*** Segurança Cibernética
*** Proteção contra Desastres Naturais
*** Proteção contra Cibercriminosos
*** Importância para Empresas
@endmindmap